### ISSUE TITLE
Python 3.13: error: ‘_PyLong_Copy’ was not declared in this scope; did you mean ‘PyLong_Type’?

### ISSUE THREAD

**Issue by penguinpee** [Ezibenroc/PyRoaringBitMap#101]
This a very early note that `pyroaring` needs some work for Python 3.13. Fedora is planning to move to Python 3.13 in release 41, which will be released about a year from now. Work on changes for Fedora 41 will start in about six months.

Fedora Python folks are rebuilding all Python packages against Python 3.13. This brought up the following error:

```python
pyroaring/pyroaring.cpp: In function ‘PyObject* __Pyx_PyLong_AbsNeg(PyObject*)’:
pyroaring/pyroaring.cpp:45414:26: error: ‘_PyLong_Copy’ was not declared in this scope; did you mean ‘PyLong_Type’?
45414 |         PyObject *copy = _PyLong_Copy((PyLongObject*)n);
      |                          ^~~~~~~~~~~~
      |                          PyLong_Type
```

More information should become available. I'll keep this issue in sync with our Bugzilla [ticket](https://bugzilla.redhat.com/show_bug.cgi?id=2247029). More information regarding changes in Python 3.13 is available upstream:

https://docs.python.org/3.13/whatsnew/3.13.html

**Comment by Ezibenroc** [comment]
Thank you for reporting. I am not sure there is much to do on pyroaring side, this is most likely a Cython issue. This might even be fixed in CPython side, if they change their plan before the release.
Anyway, I will keep this open for tracking the issue.

Most likely related to this discussion: https://discuss.python.org/t/python-3-13-alpha-1-contains-breaking-changes-whats-the-plan/37490

**Comment by penguinpee** [comment]
The issue appears to be resolved. I didn't dig into what exactly changed to make it work. We are currently on Cython 3.0.6.
