### ISSUE TITLE
include update() method to take an array of values

### ISSUE THREAD

**Issue by brentp** [Ezibenroc/PyRoaringBitMap#13]
with ctypes, adding a single element at a time (when it's not feasible to send an array to the constructor) is slow. Would be nice to have an update() method that would have only a single ctypes call.

**Comment by brentp** [comment]
I got around this by just using `bm |= Bitmap(new_values)` which seems pretty fast.
So feel free to close this issue, though I think having an update() to match the set interface would be nice.

**Comment by Ezibenroc** [comment]
Good point, I also think that we should match the set interface.

CRoaring does not have yet an update function, so we are currently forced to use the `bm |= Bitmap(new_values)` that you suggest. It is several order of magnitude faster than calling `add` for each value when there are thousands of values. However, it is not the best we can do, since instanciating a new bitmap has certainly a non negligible overhead.

I have created an issue in CRoaring: https://github.com/RoaringBitmap/CRoaring/issues/54

**Comment by lemire** [comment]
Version 0.2.3 has a function with the following signature...

```
void roaring_bitmap_add_many(roaring_bitmap_t * r, size_t n_args, const uint32_t *vals);
```

which could be handy.

**Comment by Ezibenroc** [comment]
Thank you @lemire.
`update()` method added in https://github.com/Ezibenroc/PyRoaringBitMap/commit/b58749d4fac7af035364e3603a5579cebbdbcf41
