### ISSUE TITLE
Consider making use of new iterators...

### ISSUE THREAD

**Issue by lemire** [Ezibenroc/PyRoaringBitMap#17]
With latest CRoaring, we have iterators that could be useful...

```
roaring_uint32_iterator_t  i;
roaring_init_iterator(r1, &i);
while(i.has_value) {
   //use: i.current_value
   roaring_advance_uint32_iterator(i);
}
```

**Comment by Ezibenroc** [comment]
Done in https://github.com/Ezibenroc/PyRoaringBitMap/commit/f7ad83396c8e470489fa00995c859744ac10644c.
It reduced a bit the time taken to iterate on a whole bitmap (see https://github.com/Ezibenroc/PyRoaringBitMap/commit/f21395744cc1250be1c08861d4d2e104f611122f).
It also reduced a lot the time to iterate on a sub-part of the bitmap, since with `roaring_bitmap_to_uint32_array` the complexity was linear in the size of the bitmap, even to simply iterate on the first 10 elements.
