### ISSUE TITLE
Benchmark against python-croaring

### ISSUE THREAD

**Issue by lemire** [Ezibenroc/PyRoaringBitMap#22]
See https://github.com/sunzhaoping/python-croaring/issues/1

**Comment by Ezibenroc** [comment]
I added python-croaring in my benchmark: https://github.com/Ezibenroc/PyRoaringBitMap/commit/1e57a10a0bae8c92fd6eb5d0cd37b30d45689da1

Here are the results, obtained on my laptop with the version 6d8f4c3f25bfbfb1e098901b70b8a572f5622c4c of pyroaring and the version https://github.com/sunzhaoping/python-croaring/commit/8208469f461c3673d472835f6894a0df61503c1f of python-croaring.

  operation                        | pyroaring  | python-croaring  | roaringbitmap  | set       | sortedcontainers
  ---------------------------------| -----------| -----------------| ---------------| ----------| ------------------
  range constructor                | 1.73e-04   | 1.68e+00         | 9.85e-05       | 5.28e-02  | 1.88e-01
  ordered list constructor         | 3.31e-02   | 1.75e+00         | 1.26e-01       | 1.55e-01  | 5.00e-01
  list constructor                 | 1.25e-01   | 1.79e+00         | 1.54e-01       | 9.37e-02  | 4.47e-01
  ordered array constructor        | 3.82e-03   | 1.67e+00         | 2.87e-01       | 8.21e-02  | 2.78e-01
  array constructor                | 1.19e-01   | 1.82e+00         | 4.85e-01       | 1.40e-01  | 4.97e-01
  element addition                 | 9.48e-07   | 2.34e-06         | 8.89e-06       | 1.61e-07  | 8.85e-07
  element removal                  | 2.14e-06   | 2.62e-06         | 9.82e-06       | 1.41e-07  | 3.64e-07
  membership test                  | 9.90e-08   | 5.16e-06         | 8.91e-07       | 7.80e-08  | 4.40e-07
  union                            | 1.79e-04   | 2.04e-04         | 1.76e-04       | 1.36e-01  | 9.10e-01
  intersection                     | 8.96e-04   | 9.31e-04         | 9.47e-04       | 4.92e-02  | 1.52e-01
  difference                       | 1.80e-04   | 1.98e-04         | 1.67e-04       | 1.27e-01  | 4.07e-01
  symmetric diference              | 1.89e-04   | 2.01e-04         | 2.09e-04       | 1.74e-01  | 7.61e-01
  equality test                    | 8.21e-05   | 8.44e-05         | 6.26e-05       | 1.87e-02  | 1.84e-02
  subset test                      | 9.21e-05   | 5.67e+00         | 8.98e-05       | 1.89e-02  | 1.83e-02
  conversion to list               | 4.28e-02   | 2.52e+00         | 3.88e-02       | 4.87e-02  | 4.90e-02
  pickle dump & load               | 5.11e-04   | 7.29e-04         | 6.65e-04       | 2.44e-01  | 4.34e-01
  "naive" conversion to array      | 4.35e-02   | 2.52e+00         | 4.08e-02       | 1.08e-01  | 1.04e-01
  "optimized" conversion to array  | 1.29e-03   | nan              | nan            | nan       | nan
  selection                        | 9.03e-07   | 4.24e-05         | 3.71e-06       | nan       | 1.11e-05
  slice                            | 5.06e-02   | nan              | 1.41e-01       | nan       | 7.36e-01

On some operations (e.g. union or intersection), python-croaring is approximately as efficient as pyroaring.

On some other operations (e.g. constructors, iterators or subset test), python-croaring is very slow. Maybe the reason is simply because the iterations are done on Python side and not on CRoaring side (e.g. [the constructor](https://github.com/sunzhaoping/python-croaring/blob/8208469f461c3673d472835f6894a0df61503c1f/croaring/__init__.py#L111-L115) iterates on all the elements, and the method `__le__` is not implemented so the subset test will also automatically iterate on all the elements).

**Comment by lemire** [comment]
Feel free to close this issue.
