### ISSUE TITLE
Provide binary wheels?

### ISSUE THREAD

**Issue by fgregg** [Ezibenroc/PyRoaringBitMap#28]
Hi,

Thanks for providing this great library! 

Would you be interested in providing binary wheels for windows, mac, and `manylinux`? 

I understand that these pre-compiled wheels will likely be slower than a version that was compiled on the end user's hardware, but having binary wheels can really lower the barrier to using a python library.

For those that want the fastest possible version, you can instruct people to install with `pip install pyroaring --no-binary`. 

If you would like provide binary wheels, I help with PRs that use Travis and appveyor.com to builld the wheels and publish to PyPi.

Thanks!

**Comment by Ezibenroc** [comment]
> Would you be interested in providing binary wheels for windows, mac, and manylinux?

If this is more convenient for the user, then yes, it is a good idea!

> I understand that these pre-compiled wheels will likely be slower than a version that was compiled on the end user's hardware

I am not familiar with Python's wheel. If we want to upload it to Pypi, can we upload one wheel per architecture? For instance, a wheel built for Intel will not be compatible with an ARM machine (or even an older Intel).

> If you would like provide binary wheels, I help with PRs that use Travis and appveyor.com to builld the wheels and publish to PyPi.

Sure, any PR is welcome!
I am especially interested to make pyroaring work on Windows. This should be possible since CRoaring works fine on Windows, but I do not know how.

**Comment by Ezibenroc** [comment]
Thanks to #30, pyroaring is now available on Windows.

You can get a binary wheel from the GitHub release page, e.g. for the last version: [0.2.2](
https://github.com/Ezibenroc/PyRoaringBitMap/releases/tag/0.2.2).

They are not on Pypi for two reasons:
- The Linux wheels of C extensions cannot be uploaded to Pypi, unless they are a [manylinux](https://github.com/pypa/manylinux) wheel (which is not currently done with pyroaring).
- I am not sure about the impact on performance. I would like to compare the two installation methods before switching to wheels for the default.
