### ISSUE TITLE
pip install fails on macOS Mohave with fatal error: 'ios' file not found

### ISSUE THREAD

**Issue by lemire** [Ezibenroc/PyRoaringBitMap#44]
The problem is as follows... (using Python 3.7)

```
$ pip install pyroaring
Collecting pyroaring
  Downloading https://files.pythonhosted.org/packages/c0/64/c9f6a46aa52f05681a3a57bfadaec71d06d5c8d958b86f053eeca7bacbeb/pyroaring-0.2.6.tar.gz (300kB)
    100% |████████████████████████████████| 307kB 3.5MB/s
Building wheels for collected packages: pyroaring
  Building wheel for pyroaring (setup.py) ... error
  Complete output from command /anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/y8/nl_pprtd12x78vqkv3px0bp40000gn/T/pip-install-od9upab6/pyroaring/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/y8/nl_pprtd12x78vqkv3px0bp40000gn/T/pip-wheel-geneq8e5 --python-tag cp36:
  Building pyroaring from C sources.
  running bdist_wheel
  running build
  running build_ext
  building 'pyroaring' extension
  creating build
  creating build/temp.macosx-10.7-x86_64-3.6
  creating build/temp.macosx-10.7-x86_64-3.6/pyroaring
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -I/anaconda3/include/python3.6m -c pyroaring/pyroaring.cpp -o build/temp.macosx-10.7-x86_64-3.6/pyroaring/pyroaring.o -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -O3 -march=native
  warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  pyroaring/pyroaring.cpp:646:10: fatal error: 'ios' file not found
  #include "ios"
           ^~~~~
  1 warning and 1 error generated.
  error: command 'gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for pyroaring
  Running setup.py clean for pyroaring
Failed to build pyroaring
Installing collected packages: pyroaring
  Running setup.py install for pyroaring ... error
    Complete output from command /anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/y8/nl_pprtd12x78vqkv3px0bp40000gn/T/pip-install-od9upab6/pyroaring/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/y8/nl_pprtd12x78vqkv3px0bp40000gn/T/pip-record-36zin8uc/install-record.txt --single-version-externally-managed --compile:
    Building pyroaring from C sources.
    running install
    running build
    running build_ext
    building 'pyroaring' extension
    creating build
    creating build/temp.macosx-10.7-x86_64-3.6
    creating build/temp.macosx-10.7-x86_64-3.6/pyroaring
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -I/anaconda3/include/python3.6m -c pyroaring/pyroaring.cpp -o build/temp.macosx-10.7-x86_64-3.6/pyroaring/pyroaring.o -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -O3 -march=native
    warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    pyroaring/pyroaring.cpp:646:10: fatal error: 'ios' file not found
    #include "ios"
             ^~~~~
    1 warning and 1 error generated.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/y8/nl_pprtd12x78vqkv3px0bp40000gn/T/pip-install-od9upab6/pyroaring/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/y8/nl_pprtd12x78vqkv3px0bp40000gn/T/pip-record-36zin8uc/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/y8/nl_pprtd12x78vqkv3px0bp40000gn/T/pip-install-od9upab6/pyroaring/
```

The fix is to set `MACOSX_DEPLOYMENT_TARGET` like so:

```
MACOSX_DEPLOYMENT_TARGET=10.14 pip install pyroaring
```

Maybe this ought to appear in the README? Instructions for macOS Mohave?

**Comment by Axeldnahcram** [comment]
Ok so I have added CFLAGS='-stdlib=libc++' in front of the pip install and it worked just fine no idea why. Here is the full command 
`CFLAGS='-stdlib=libc++' pip install pyroaring`

**Comment by Ezibenroc** [comment]
Thanks for reporting the issue. I used the argument `-mmacosx-version-min=10.14`, it should be equivalent.

I do not own a Mac and this MacOS version is apparently not the one used on Travis.
Could you test with commit 2803234748f3054ac80e4141e8c1681e5ecc410a and tell me if it works? You will need the `Cython` package.
```
git clone --recurse-submodules https://github.com/Ezibenroc/PyRoaringBitMap.git
cd PyRoaringBitMap
git checkout 2803234748f3054ac80e4141e8c1681e5ecc410a
python setup.py build_ext -i
```

**Comment by Axeldnahcram** [comment]
It does work however 12 issues came up. Here is the full log:
`Building pyroaring from Cython sources.
Compiling pyroaring/pyroaring.pyx because it changed.
[1/1] Cythonizing pyroaring/pyroaring.pyx
/anaconda3/lib/python3.7/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /Users/amarchand/opt/PyRoaringBitMap/pyroaring/pyroaring.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
warning: pyroaring/croaring.pxd:43:43: Declarations should not be declared inline.
running build_ext
building 'pyroaring' extension
creating build
creating build/temp.macosx-10.9-x86_64-3.7
creating build/temp.macosx-10.9-x86_64-3.7/pyroaring
x86_64-apple-darwin13.4.0-clang -DNDEBUG -fwrapv -O3 -Wall -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -I/usr/local/opt/libxml2/include -I/anaconda3/include/python3.7m -c pyroaring/pyroaring.cpp -o build/temp.macosx-10.9-x86_64-3.7/pyroaring/pyroaring.o -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -mmacosx-version-min=10.14 -O3 -march=native
pyroaring/pyroaring.cpp:17026:20: warning: unused variable '__pyx_mdef___pyx_array_1__reduce_cython__' [-Wunused-variable]
static PyMethodDef __pyx_mdef___pyx_array_1__reduce_cython__ = {"__reduce_cython__", (PyCFunction)__pyx_pw___pyx_array_1__reduce_cython__, METH_NOARGS, 0};
                   ^
pyroaring/pyroaring.cpp:17081:20: warning: unused variable '__pyx_mdef___pyx_array_3__setstate_cython__' [-Wunused-variable]
static PyMethodDef __pyx_mdef___pyx_array_3__setstate_cython__ = {"__setstate_cython__", (PyCFunction)__pyx_pw___pyx_array_3__setstate_cython__, METH_O, 0};
                   ^
pyroaring/pyroaring.cpp:17450:20: warning: unused variable '__pyx_mdef___pyx_MemviewEnum_1__reduce_cython__' [-Wunused-variable]
static PyMethodDef __pyx_mdef___pyx_MemviewEnum_1__reduce_cython__ = {"__reduce_cython__", (PyCFunction)__pyx_pw___pyx_MemviewEnum_1__reduce_cython__, METH_NOARGS, 0};
                   ^
pyroaring/pyroaring.cpp:17683:20: warning: unused variable '__pyx_mdef___pyx_MemviewEnum_3__setstate_cython__' [-Wunused-variable]
static PyMethodDef __pyx_mdef___pyx_MemviewEnum_3__setstate_cython__ = {"__setstate_cython__", (PyCFunction)__pyx_pw___pyx_MemviewEnum_3__setstate_cython__, METH_O, 0};
                   ^
pyroaring/pyroaring.cpp:21442:20: warning: unused variable '__pyx_mdef_15View_dot_MemoryView_10memoryview_17is_c_contig' [-Wunused-variable]
static PyMethodDef __pyx_mdef_15View_dot_MemoryView_10memoryview_17is_c_contig = {"is_c_contig", (PyCFunction)__pyx_memoryview_is_c_contig, METH_NOARGS, 0};
                   ^
pyroaring/pyroaring.cpp:21514:20: warning: unused variable '__pyx_mdef_15View_dot_MemoryView_10memoryview_19is_f_contig' [-Wunused-variable]
static PyMethodDef __pyx_mdef_15View_dot_MemoryView_10memoryview_19is_f_contig = {"is_f_contig", (PyCFunction)__pyx_memoryview_is_f_contig, METH_NOARGS, 0};
                   ^
pyroaring/pyroaring.cpp:21586:20: warning: unused variable '__pyx_mdef_15View_dot_MemoryView_10memoryview_21copy' [-Wunused-variable]
static PyMethodDef __pyx_mdef_15View_dot_MemoryView_10memoryview_21copy = {"copy", (PyCFunction)__pyx_memoryview_copy, METH_NOARGS, 0};
                   ^
pyroaring/pyroaring.cpp:21678:20: warning: unused variable '__pyx_mdef_15View_dot_MemoryView_10memoryview_23copy_fortran' [-Wunused-variable]
static PyMethodDef __pyx_mdef_15View_dot_MemoryView_10memoryview_23copy_fortran = {"copy_fortran", (PyCFunction)__pyx_memoryview_copy_fortran, METH_NOARGS, 0};
                   ^
pyroaring/pyroaring.cpp:21769:20: warning: unused variable '__pyx_mdef___pyx_memoryview_1__reduce_cython__' [-Wunused-variable]
static PyMethodDef __pyx_mdef___pyx_memoryview_1__reduce_cython__ = {"__reduce_cython__", (PyCFunction)__pyx_pw___pyx_memoryview_1__reduce_cython__, METH_NOARGS, 0};
                   ^
pyroaring/pyroaring.cpp:21824:20: warning: unused variable '__pyx_mdef___pyx_memoryview_3__setstate_cython__' [-Wunused-variable]
static PyMethodDef __pyx_mdef___pyx_memoryview_3__setstate_cython__ = {"__setstate_cython__", (PyCFunction)__pyx_pw___pyx_memoryview_3__setstate_cython__, METH_O, 0};
                   ^
pyroaring/pyroaring.cpp:24639:20: warning: unused variable '__pyx_mdef___pyx_memoryviewslice_1__reduce_cython__' [-Wunused-variable]
static PyMethodDef __pyx_mdef___pyx_memoryviewslice_1__reduce_cython__ = {"__reduce_cython__", (PyCFunction)__pyx_pw___pyx_memoryviewslice_1__reduce_cython__, METH_NOARGS, 0};
                   ^
pyroaring/pyroaring.cpp:24694:20: warning: unused variable '__pyx_mdef___pyx_memoryviewslice_3__setstate_cython__' [-Wunused-variable]
static PyMethodDef __pyx_mdef___pyx_memoryviewslice_3__setstate_cython__ = {"__setstate_cython__", (PyCFunction)__pyx_pw___pyx_memoryviewslice_3__setstate_cython__, METH_O, 0};
                   ^
12 warnings generated.
x86_64-apple-darwin13.4.0-clang -DNDEBUG -fwrapv -O3 -Wall -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -I/usr/local/opt/libxml2/include -I/anaconda3/include/python3.7m -c pyroaring/roaring.c -o build/temp.macosx-10.9-x86_64-3.7/pyroaring/roaring.o -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -mmacosx-version-min=10.14 -O3 -march=native
creating build/lib.macosx-10.9-x86_64-3.7
x86_64-apple-darwin13.4.0-clang++ -bundle -undefined dynamic_lookup -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/anaconda3/lib -L/anaconda3/lib -flto -Wl,-export_dynamic -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/anaconda3/lib -L/anaconda3/lib -L/usr/local/opt/libxml2/lib -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -I/usr/local/opt/libxml2/include -arch x86_64 build/temp.macosx-10.9-x86_64-3.7/pyroaring/pyroaring.o build/temp.macosx-10.9-x86_64-3.7/pyroaring/roaring.o -o build/lib.macosx-10.9-x86_64-3.7/pyroaring.cpython-37m-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
ld: warning: object file (build/temp.macosx-10.9-x86_64-3.7/pyroaring/pyroaring.o) was built for newer OSX version (10.14) than being linked (10.9)
ld: warning: object file (build/temp.macosx-10.9-x86_64-3.7/pyroaring/roaring.o) was built for newer OSX version (10.14) than being linked (10.9)
ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x76 0x33 ) which is not the architecture being linked (x86_64): /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
copying build/lib.macosx-10.9-x86_64-3.7/pyroaring.cpython-37m-darwin.so ->`

**Comment by Axeldnahcram** [comment]
It does work however 12 issues came up, here is the full log:

Could you test with commit [2803234](https://github.com/Ezibenroc/PyRoaringBitMap/commit/2803234748f3054ac80e4141e8c1681e5ecc410a) and tell me if it works? You will need the `Cython` package.

```
Building pyroaring from Cython sources.
Compiling pyroaring/pyroaring.pyx because it changed.
[1/1] Cythonizing pyroaring/pyroaring.pyx
/anaconda3/lib/python3.7/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /Users/amarchand/opt/PyRoaringBitMap/pyroaring/pyroaring.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
warning: pyroaring/croaring.pxd:43:43: Declarations should not be declared inline.
running build_ext
building 'pyroaring' extension
creating build
creating build/temp.macosx-10.9-x86_64-3.7
creating build/temp.macosx-10.9-x86_64-3.7/pyroaring
x86_64-apple-darwin13.4.0-clang -DNDEBUG -fwrapv -O3 -Wall -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -I/usr/local/opt/libxml2/include -I/anaconda3/include/python3.7m -c pyroaring/pyroaring.cpp -o build/temp.macosx-10.9-x86_64-3.7/pyroaring/pyroaring.o -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -mmacosx-version-min=10.14 -O3 -march=native
pyroaring/pyroaring.cpp:17026:20: warning: unused variable '__pyx_mdef___pyx_array_1__reduce_cython__' [-Wunused-variable]
static PyMethodDef __pyx_mdef___pyx_array_1__reduce_cython__ = {"__reduce_cython__", (PyCFunction)__pyx_pw___pyx_array_1__reduce_cython__, METH_NOARGS, 0};
                   ^
pyroaring/pyroaring.cpp:17081:20: warning: unused variable '__pyx_mdef___pyx_array_3__setstate_cython__' [-Wunused-variable]
static PyMethodDef __pyx_mdef___pyx_array_3__setstate_cython__ = {"__setstate_cython__", (PyCFunction)__pyx_pw___pyx_array_3__setstate_cython__, METH_O, 0};
                   ^
pyroaring/pyroaring.cpp:17450:20: warning: unused variable '__pyx_mdef___pyx_MemviewEnum_1__reduce_cython__' [-Wunused-variable]
static PyMethodDef __pyx_mdef___pyx_MemviewEnum_1__reduce_cython__ = {"__reduce_cython__", (PyCFunction)__pyx_pw___pyx_MemviewEnum_1__reduce_cython__, METH_NOARGS, 0};
                   ^
pyroaring/pyroaring.cpp:17683:20: warning: unused variable '__pyx_mdef___pyx_MemviewEnum_3__setstate_cython__' [-Wunused-variable]
static PyMethodDef __pyx_mdef___pyx_MemviewEnum_3__setstate_cython__ = {"__setstate_cython__", (PyCFunction)__pyx_pw___pyx_MemviewEnum_3__setstate_cython__, METH_O, 0};
                   ^
pyroaring/pyroaring.cpp:21442:20: warning: unused variable '__pyx_mdef_15View_dot_MemoryView_10memoryview_17is_c_contig' [-Wunused-variable]
static PyMethodDef __pyx_mdef_15View_dot_MemoryView_10memoryview_17is_c_contig = {"is_c_contig", (PyCFunction)__pyx_memoryview_is_c_contig, METH_NOARGS, 0};
                   ^
pyroaring/pyroaring.cpp:21514:20: warning: unused variable '__pyx_mdef_15View_dot_MemoryView_10memoryview_19is_f_contig' [-Wunused-variable]
static PyMethodDef __pyx_mdef_15View_dot_MemoryView_10memoryview_19is_f_contig = {"is_f_contig", (PyCFunction)__pyx_memoryview_is_f_contig, METH_NOARGS, 0};
                   ^
pyroaring/pyroaring.cpp:21586:20: warning: unused variable '__pyx_mdef_15View_dot_MemoryView_10memoryview_21copy' [-Wunused-variable]
static PyMethodDef __pyx_mdef_15View_dot_MemoryView_10memoryview_21copy = {"copy", (PyCFunction)__pyx_memoryview_copy, METH_NOARGS, 0};
                   ^
pyroaring/pyroaring.cpp:21678:20: warning: unused variable '__pyx_mdef_15View_dot_MemoryView_10memoryview_23copy_fortran' [-Wunused-variable]
static PyMethodDef __pyx_mdef_15View_dot_MemoryView_10memoryview_23copy_fortran = {"copy_fortran", (PyCFunction)__pyx_memoryview_copy_fortran, METH_NOARGS, 0};
                   ^
pyroaring/pyroaring.cpp:21769:20: warning: unused variable '__pyx_mdef___pyx_memoryview_1__reduce_cython__' [-Wunused-variable]
static PyMethodDef __pyx_mdef___pyx_memoryview_1__reduce_cython__ = {"__reduce_cython__", (PyCFunction)__pyx_pw___pyx_memoryview_1__reduce_cython__, METH_NOARGS, 0};
                   ^
pyroaring/pyroaring.cpp:21824:20: warning: unused variable '__pyx_mdef___pyx_memoryview_3__setstate_cython__' [-Wunused-variable]
static PyMethodDef __pyx_mdef___pyx_memoryview_3__setstate_cython__ = {"__setstate_cython__", (PyCFunction)__pyx_pw___pyx_memoryview_3__setstate_cython__, METH_O, 0};
                   ^
pyroaring/pyroaring.cpp:24639:20: warning: unused variable '__pyx_mdef___pyx_memoryviewslice_1__reduce_cython__' [-Wunused-variable]
static PyMethodDef __pyx_mdef___pyx_memoryviewslice_1__reduce_cython__ = {"__reduce_cython__", (PyCFunction)__pyx_pw___pyx_memoryviewslice_1__reduce_cython__, METH_NOARGS, 0};
                   ^
pyroaring/pyroaring.cpp:24694:20: warning: unused variable '__pyx_mdef___pyx_memoryviewslice_3__setstate_cython__' [-Wunused-variable]
static PyMethodDef __pyx_mdef___pyx_memoryviewslice_3__setstate_cython__ = {"__setstate_cython__", (PyCFunction)__pyx_pw___pyx_memoryviewslice_3__setstate_cython__, METH_O, 0};
                   ^
12 warnings generated.
x86_64-apple-darwin13.4.0-clang -DNDEBUG -fwrapv -O3 -Wall -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -I/usr/local/opt/libxml2/include -I/anaconda3/include/python3.7m -c pyroaring/roaring.c -o build/temp.macosx-10.9-x86_64-3.7/pyroaring/roaring.o -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -mmacosx-version-min=10.14 -O3 -march=native
creating build/lib.macosx-10.9-x86_64-3.7
x86_64-apple-darwin13.4.0-clang++ -bundle -undefined dynamic_lookup -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/anaconda3/lib -L/anaconda3/lib -flto -Wl,-export_dynamic -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/anaconda3/lib -L/anaconda3/lib -L/usr/local/opt/libxml2/lib -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -I/usr/local/opt/libxml2/include -arch x86_64 build/temp.macosx-10.9-x86_64-3.7/pyroaring/pyroaring.o build/temp.macosx-10.9-x86_64-3.7/pyroaring/roaring.o -o build/lib.macosx-10.9-x86_64-3.7/pyroaring.cpython-37m-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
ld: warning: object file (build/temp.macosx-10.9-x86_64-3.7/pyroaring/pyroaring.o) was built for newer OSX version (10.14) than being linked (10.9)
ld: warning: object file (build/temp.macosx-10.9-x86_64-3.7/pyroaring/roaring.o) was built for newer OSX version (10.14) than being linked (10.9)
ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x76 0x33 ) which is not the architecture being linked (x86_64): /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
copying build/lib.macosx-10.9-x86_64-3.7/pyroaring.cpython-37m-darwin.so ->
```

**Comment by Ezibenroc** [comment]
> It does work however 12 issues came up, here is the full log:

Not a big deal, I also have these warnings on my machine since quite a long time. Cython is just producing unused variables for some reason.
